version: '3.7'

services:
  postgres-server:
    container_name: postgres
    image: postgres:14.2-alpine
    networks:
      - network-zabbix
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data/pgdata

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:ubuntu-6.0.3
    networks:
      network-zabbix:
    restart: always
    ports:
      - "10051:10051"
    volumes:
      - ./config:/etc/zabbix
      - zabbix-data:/usr/lib/zabbix/alertscripts
      - zabbix-data:/usr/lib/zabbix/externalscripts
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - postgres-server

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-pgsql:ubuntu-6.0.3
    networks:
      - network-zabbix
    restart: always
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PHP_TZ: ${TZ}
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server

  grafana:
    container_name: grafana
    image: grafana/grafana:8.4.6
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-data:/etc/grafana/provisioning
    networks:
      - network-zabbix
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      - GRAFANA_VERSION=latest
    depends_on:
      - zabbix-server

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent:alpine-6.0.3
    user: root
    networks:
      network-zabbix:
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - "10050:10050"
    environment:
      - ZBX_HOSTNAME=zabbix-server
      - ZBX_SERVER_HOST=zabbix-server

networks:
  network-zabbix:

volumes:
  grafana-data:
  postgres-data:
  zabbix-data:
